In [2]:
import numpy as np

In [5]:
a = np.empty(4, dtype = int)
print(a)

[ 1912410589 -1758581171  1093573117   993901117]


In [18]:
a=np.random.rand(4,4)*10
a

array([[0.96269225, 7.08412187, 9.56943762, 8.76816339],
       [2.77693829, 8.07507908, 2.90687434, 9.69396988],
       [2.58852667, 5.52359894, 6.24058134, 6.01603032],
       [4.4158287 , 3.8593616 , 7.78387321, 9.62342861]])

In [20]:
a=np.random.randint(10,size=(4,4))
a

array([[2, 4, 8, 2],
       [3, 0, 2, 7],
       [2, 8, 5, 1],
       [0, 2, 6, 1]])