In [2]:
import numpy as np

In [3]:
a = np.empty(4, dtype = int)
print(a)

[-361223063 -484631567  -79205658 1403719610]


In [4]:
a=np.random.rand(4,4)*10
a

array([[3.56933551e+00, 5.16449556e-01, 1.26009023e+00, 4.38677616e+00],
       [6.96060839e+00, 1.55360676e+00, 8.43290187e+00, 2.53445475e-01],
       [6.04661945e+00, 1.88032386e+00, 4.56824709e+00, 7.37365062e-03],
       [3.38257641e+00, 1.72447905e+00, 4.54139479e+00, 2.18981213e+00]])

In [5]:
a=np.random.randint(10,size=(4,4))
a

array([[7, 7, 6, 1],
       [3, 1, 0, 5],
       [5, 4, 8, 2],
       [8, 4, 7, 2]])

In [6]:
np.random.randint(10, 4)

ValueError: low >= high

In [7]:
np.random.rand()

0.8823292776756786